### ISSUE TITLE
Not an issue: Request: Restrict range based off of the server side setting

### ISSUE THREAD

**Issue by SirFrostingham** [Elmegaard/QuickStash#2]
It’s a-ok if you close it with no change.

It would be cool to make players travel back to the vicinity of their base, before the key works. Maybe There is a message, get closer to your base. That way if you have multiple bases, they sort of know they were close to Base A and the stuff probably went there instead of Base B. Maybe some server owners restrict it to very close to a base. Fun option. Thanks. Cool mod!

**Comment by Elmegaard** [comment]
The plan is to make it only work when you are in a base if possible. I just haven't gotten there yet and decided to release it anyway.

**Comment by SirFrostingham** [comment]
Awesome! Love it. Thank you. Have a good one.
