### ISSUE TITLE
Crashing due to leak

### ISSUE THREAD

**Issue by rbau28** [Elmegaard/QuickStash#4]
[Player.log](https://github.com/Elmegaard/QuickStash/files/8831344/Player.log)

Internal: JobTempAlloc has allocations that are more than 4 frames old - this is not allowed and likely a leak
Occurs randomly, can also be triggered when using the hotkey.

**Comment by TheElec** [comment]
Here two more from different users
[Player (1).log](https://github.com/Elmegaard/QuickStash/files/8831350/Player.1.log)
[Player.log](https://github.com/Elmegaard/QuickStash/files/8831352/Player.log)

**Comment by Elmegaard** [comment]
Should be fixed in the next version.
